# Generated by Django 4.2.6 on 2023-11-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='sproduct',
        ),
    ]
