# Generated by Django 4.2.6 on 2023-11-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_product_sproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sproduct',
            new_name='special_product',
        ),
    ]
