# Generated by Django 4.2.6 on 2023-11-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_sproduct_special_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='special_product',
            new_name='product',
        ),
    ]
