# Generated by Django 4.2.6 on 2023-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_sjst_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='spc_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('p_price', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('tozih', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='aks')),
            ],
        ),
    ]
