# Generated by Django 4.2.6 on 2023-11-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sale_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='electric',
            new_name='electric_product',
        ),
    ]
