# Generated by Django 4.2.6 on 2023-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjst_product',
            name='category',
            field=models.ManyToManyField(to='app1.category'),
        ),
        migrations.AddField(
            model_name='spc_product',
            name='category',
            field=models.ManyToManyField(to='app1.category'),
        ),
    ]
