# Generated by Django 4.2.6 on 2023-11-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_sjst_product_category_spc_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_product',
            name='category',
            field=models.ManyToManyField(to='app1.category'),
        ),
    ]
