# Generated by Django 4.2.6 on 2023-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_sale_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='sundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('tozih', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='aks')),
            ],
        ),
    ]
