# Generated by Django 4.2.6 on 2023-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_sundry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='electric_product',
        ),
        migrations.RemoveField(
            model_name='sale_product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sjst_product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spc_product',
            name='category',
        ),
        migrations.DeleteModel(
            name='sundry',
        ),
        migrations.AddField(
            model_name='product',
            name='categoryid',
            field=models.ManyToManyField(to='app1.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='sale_product',
        ),
        migrations.DeleteModel(
            name='sjst_product',
        ),
        migrations.DeleteModel(
            name='spc_product',
        ),
    ]
