# Generated by Django 4.2.6 on 2023-11-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_delete_electric_product_remove_sale_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_price',
            new_name='pprice',
        ),
    ]
