# Generated by Django 4.2.6 on 2023-11-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_p_price_product_pprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryid',
            new_name='category',
        ),
    ]
