# Generated by Django 4.2.6 on 2023-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='app1.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
