# Generated by Django 4.2.6 on 2023-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_product_category_alter_product_pprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
