# Generated by Django 4.2.6 on 2023-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moshakhasat',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
