# Generated by Django 4.2.6 on 2023-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_product_moshakhasat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garenty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
