# Generated by Django 4.2.6 on 2023-12-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='family',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='lname',
        ),
    ]
