# Generated by Django 4.2.6 on 2023-12-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان طبقه'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.CharField(max_length=500, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(upload_to='aks', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='new',
            name='source',
            field=models.CharField(max_length=50, verbose_name='منبع خبر'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=30, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='app1.category', verbose_name='طبقه بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='garenty',
            field=models.CharField(max_length=100, null=True, verbose_name='وضعیت گارانتی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='aks', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='moshakhasat',
            field=models.CharField(max_length=500, null=True, verbose_name='مشخصات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pprice',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='قیمت قبل از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=30, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tozih',
            field=models.CharField(max_length=500, verbose_name='توضیحات محصول'),
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='aks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
