# Generated by Django 4.2.6 on 2023-12-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیامها'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
    ]
