# Generated by Django 4.2.6 on 2023-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
