# Generated by Django 4.2.6 on 2023-12-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_new_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
