# Generated by Django 4.2.6 on 2024-02-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_faktor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pprice',
        ),
    ]
