# Generated by Django 4.2.6 on 2024-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_product_pprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name=' قیمت ویژه'),
        ),
    ]
