# Generated by Django 4.2.6 on 2024-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_product_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(null=True, verbose_name='ویژه'),
        ),
    ]
